plugins {
    id 'com.android.application'
}
android {
    namespace "com.pwdgen.app"
    compileSdk 35
    defaultConfig {
        applicationId "com.pwdgen.app"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
dependencies {}
